#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci
  i = 2
  fibo = [1,2]
  while i < 100
    fibo[i] = fibo[i-1] + fibo[i-2]
    if fibo[i] > 4000000 then
      break
    end
    i += 1
  end 
  
  n = 0
  j = 0
    for j in j...fibo.length do
      if fibo[j].even?
        n = n + fibo[j]
      end
    end
    print n
    
end

fibonacci()
    